# Generated by Django 6.0.6 on 2026-06-24 18:39

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0002_organizationinvitation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("FREE", "Free"),
                            ("PRO", "Pro"),
                            ("ENTERPRISE", "Enterprise"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("max_users", models.PositiveIntegerField(default=0)),
                ("api_limit", models.PositiveIntegerField(default=0)),
                (
                    "stripe_price_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "billing_plans",
                "ordering": ["price"],
            },
        ),
        migrations.CreateModel(
            name="PaymentEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(max_length=255)),
                ("stripe_event_id", models.CharField(max_length=255, unique=True)),
                ("payload", models.JSONField()),
                ("processed", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_events",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "billing_payment_events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["stripe_event_id"],
                        name="billing_pay_stripe__454eec_idx",
                    ),
                    models.Index(
                        fields=["event_type"], name="billing_pay_event_t_3888ab_idx"
                    ),
                    models.Index(
                        fields=["processed"], name="billing_pay_process_9cb15e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("TRIALING", "Trialing"),
                            ("PAST_DUE", "Past Due"),
                            ("CANCELED", "Canceled"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("current_period_start", models.DateTimeField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="organizations.organization",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="billing.plan",
                    ),
                ),
            ],
            options={
                "db_table": "billing_subscriptions",
                "indexes": [
                    models.Index(
                        fields=["status"], name="billing_sub_status_9d3b01_idx"
                    ),
                    models.Index(
                        fields=["stripe_customer_id"],
                        name="billing_sub_stripe__f2f5cc_idx",
                    ),
                    models.Index(
                        fields=["stripe_subscription_id"],
                        name="billing_sub_stripe__4b5970_idx",
                    ),
                ],
            },
        ),
    ]
